// Generated by tools/generate-drawables.mjs. Do not edit.
// Regenerate with: node tools/generate-drawables.mjs
package io.ericchernuka.pintprogress

import io.ericchernuka.pintprogress.core.PintAsset
import io.ericchernuka.pintprogress.core.PintFieldLayout
import io.ericchernuka.pintprogress.core.PintFillAsset

/** Compile-time drawable mappings generated alongside the drawable vectors. */
internal fun PintAsset.drawableRes(layout: PintFieldLayout): Int = when (layout) {
    PintFieldLayout.PICKER -> when (this) {
        PintAsset.PINT_00 -> R.drawable.pint_00_compact
        PintAsset.PINT_05 -> R.drawable.pint_05_compact
        PintAsset.PINT_10 -> R.drawable.pint_10_compact
        PintAsset.PINT_15 -> R.drawable.pint_15_compact
        PintAsset.PINT_20 -> R.drawable.pint_20_compact
        PintAsset.PINT_25 -> R.drawable.pint_25_compact
        PintAsset.PINT_30 -> R.drawable.pint_30_compact
        PintAsset.PINT_35 -> R.drawable.pint_35_compact
        PintAsset.PINT_40 -> R.drawable.pint_40_compact
        PintAsset.PINT_45 -> R.drawable.pint_45_compact
        PintAsset.PINT_50 -> R.drawable.pint_50_compact
        PintAsset.PINT_55 -> R.drawable.pint_55_compact
        PintAsset.PINT_60 -> R.drawable.pint_60_compact
        PintAsset.PINT_65 -> R.drawable.pint_65_compact
        PintAsset.PINT_70 -> R.drawable.pint_70_compact
        PintAsset.PINT_75 -> R.drawable.pint_75_compact
        PintAsset.PINT_80 -> R.drawable.pint_80_compact
        PintAsset.PINT_85 -> R.drawable.pint_85_compact
        PintAsset.PINT_90 -> R.drawable.pint_90_compact
        PintAsset.PINT_95 -> R.drawable.pint_95_compact
        PintAsset.FULL_BUBBLES -> R.drawable.pint_full_bubbles_compact
        PintAsset.DRAINING -> R.drawable.pint_draining_compact
        PintAsset.UNAVAILABLE -> R.drawable.pint_unavailable_compact
    }
    PintFieldLayout.REGULAR -> when (this) {
        PintAsset.PINT_00 -> R.drawable.pint_00
        PintAsset.PINT_05 -> R.drawable.pint_05
        PintAsset.PINT_10 -> R.drawable.pint_10
        PintAsset.PINT_15 -> R.drawable.pint_15
        PintAsset.PINT_20 -> R.drawable.pint_20
        PintAsset.PINT_25 -> R.drawable.pint_25
        PintAsset.PINT_30 -> R.drawable.pint_30
        PintAsset.PINT_35 -> R.drawable.pint_35
        PintAsset.PINT_40 -> R.drawable.pint_40
        PintAsset.PINT_45 -> R.drawable.pint_45
        PintAsset.PINT_50 -> R.drawable.pint_50
        PintAsset.PINT_55 -> R.drawable.pint_55
        PintAsset.PINT_60 -> R.drawable.pint_60
        PintAsset.PINT_65 -> R.drawable.pint_65
        PintAsset.PINT_70 -> R.drawable.pint_70
        PintAsset.PINT_75 -> R.drawable.pint_75
        PintAsset.PINT_80 -> R.drawable.pint_80
        PintAsset.PINT_85 -> R.drawable.pint_85
        PintAsset.PINT_90 -> R.drawable.pint_90
        PintAsset.PINT_95 -> R.drawable.pint_95
        PintAsset.FULL_BUBBLES -> R.drawable.pint_full_bubbles
        PintAsset.DRAINING -> R.drawable.pint_draining
        PintAsset.UNAVAILABLE -> R.drawable.pint_unavailable
    }
    PintFieldLayout.COMPACT -> when (this) {
        PintAsset.PINT_00 -> R.drawable.pint_00_compact
        PintAsset.PINT_05 -> R.drawable.pint_05_compact
        PintAsset.PINT_10 -> R.drawable.pint_10_compact
        PintAsset.PINT_15 -> R.drawable.pint_15_compact
        PintAsset.PINT_20 -> R.drawable.pint_20_compact
        PintAsset.PINT_25 -> R.drawable.pint_25_compact
        PintAsset.PINT_30 -> R.drawable.pint_30_compact
        PintAsset.PINT_35 -> R.drawable.pint_35_compact
        PintAsset.PINT_40 -> R.drawable.pint_40_compact
        PintAsset.PINT_45 -> R.drawable.pint_45_compact
        PintAsset.PINT_50 -> R.drawable.pint_50_compact
        PintAsset.PINT_55 -> R.drawable.pint_55_compact
        PintAsset.PINT_60 -> R.drawable.pint_60_compact
        PintAsset.PINT_65 -> R.drawable.pint_65_compact
        PintAsset.PINT_70 -> R.drawable.pint_70_compact
        PintAsset.PINT_75 -> R.drawable.pint_75_compact
        PintAsset.PINT_80 -> R.drawable.pint_80_compact
        PintAsset.PINT_85 -> R.drawable.pint_85_compact
        PintAsset.PINT_90 -> R.drawable.pint_90_compact
        PintAsset.PINT_95 -> R.drawable.pint_95_compact
        PintAsset.FULL_BUBBLES -> R.drawable.pint_full_bubbles_compact
        PintAsset.DRAINING -> R.drawable.pint_draining_compact
        PintAsset.UNAVAILABLE -> R.drawable.pint_unavailable_compact
    }
    PintFieldLayout.ICON_ONLY -> when (this) {
        PintAsset.PINT_00 -> R.drawable.pint_00_icon
        PintAsset.PINT_05 -> R.drawable.pint_05_icon
        PintAsset.PINT_10 -> R.drawable.pint_10_icon
        PintAsset.PINT_15 -> R.drawable.pint_15_icon
        PintAsset.PINT_20 -> R.drawable.pint_20_icon
        PintAsset.PINT_25 -> R.drawable.pint_25_icon
        PintAsset.PINT_30 -> R.drawable.pint_30_icon
        PintAsset.PINT_35 -> R.drawable.pint_35_icon
        PintAsset.PINT_40 -> R.drawable.pint_40_icon
        PintAsset.PINT_45 -> R.drawable.pint_45_icon
        PintAsset.PINT_50 -> R.drawable.pint_50_icon
        PintAsset.PINT_55 -> R.drawable.pint_55_icon
        PintAsset.PINT_60 -> R.drawable.pint_60_icon
        PintAsset.PINT_65 -> R.drawable.pint_65_icon
        PintAsset.PINT_70 -> R.drawable.pint_70_icon
        PintAsset.PINT_75 -> R.drawable.pint_75_icon
        PintAsset.PINT_80 -> R.drawable.pint_80_icon
        PintAsset.PINT_85 -> R.drawable.pint_85_icon
        PintAsset.PINT_90 -> R.drawable.pint_90_icon
        PintAsset.PINT_95 -> R.drawable.pint_95_icon
        PintAsset.FULL_BUBBLES -> R.drawable.pint_full_bubbles_icon
        PintAsset.DRAINING -> R.drawable.pint_draining_icon
        PintAsset.UNAVAILABLE -> R.drawable.pint_unavailable_icon
    }
}

internal fun PintFillAsset.drawableRes(): Int = when (this) {
    PintFillAsset.FILL_00 -> R.drawable.pint_fill_00
    PintFillAsset.FILL_05 -> R.drawable.pint_fill_05
    PintFillAsset.FILL_10 -> R.drawable.pint_fill_10
    PintFillAsset.FILL_15 -> R.drawable.pint_fill_15
    PintFillAsset.FILL_20 -> R.drawable.pint_fill_20
    PintFillAsset.FILL_25 -> R.drawable.pint_fill_25
    PintFillAsset.FILL_30 -> R.drawable.pint_fill_30
    PintFillAsset.FILL_35 -> R.drawable.pint_fill_35
    PintFillAsset.FILL_40 -> R.drawable.pint_fill_40
    PintFillAsset.FILL_45 -> R.drawable.pint_fill_45
    PintFillAsset.FILL_50 -> R.drawable.pint_fill_50
    PintFillAsset.FILL_55 -> R.drawable.pint_fill_55
    PintFillAsset.FILL_60 -> R.drawable.pint_fill_60
    PintFillAsset.FILL_65 -> R.drawable.pint_fill_65
    PintFillAsset.FILL_70 -> R.drawable.pint_fill_70
    PintFillAsset.FILL_75 -> R.drawable.pint_fill_75
    PintFillAsset.FILL_80 -> R.drawable.pint_fill_80
    PintFillAsset.FILL_85 -> R.drawable.pint_fill_85
    PintFillAsset.FILL_90 -> R.drawable.pint_fill_90
    PintFillAsset.FILL_95 -> R.drawable.pint_fill_95
    PintFillAsset.FILL_FULL_FOAM -> R.drawable.pint_fill_full_foam
    PintFillAsset.FILL_DRAINING -> R.drawable.pint_fill_draining
    PintFillAsset.FILL_UNAVAILABLE -> R.drawable.pint_fill_unavailable
}
