// Generated by tools/generate-drawables.mjs. Do not edit.
package io.ericchernuka.pintprogress.core

/** Static drawable frames generated with the vector assets. */
enum class PintAsset {
    PINT_00,
    PINT_05,
    PINT_10,
    PINT_15,
    PINT_20,
    PINT_25,
    PINT_30,
    PINT_35,
    PINT_40,
    PINT_45,
    PINT_50,
    PINT_55,
    PINT_60,
    PINT_65,
    PINT_70,
    PINT_75,
    PINT_80,
    PINT_85,
    PINT_90,
    PINT_95,
    FULL_BUBBLES,
    DRAINING,
    UNAVAILABLE
}

fun displayFor(frame: PintFrame): Pair<PintAsset, String> = when (frame) {
    PintFrame.Unavailable -> PintAsset.UNAVAILABLE to ""
    is PintFrame.Steady -> PintAsset.entries[frame.progress.fillBucket] to frame.progress.completed.completedText()
    is PintFrame.FullBubbles -> PintAsset.FULL_BUBBLES to frame.completed.completedText()
    is PintFrame.Draining -> PintAsset.DRAINING to frame.completed.completedText()
}

private fun Int.completedText() = if (this == 0) "" else toString()
