// Generated by tools/generate-drawables.mjs. Do not edit.
package io.ericchernuka.pintprogress.core

/** Static drawable frames generated with the vector assets. */
enum class PintFillAsset {
    FILL_00,
    FILL_05,
    FILL_10,
    FILL_15,
    FILL_20,
    FILL_25,
    FILL_30,
    FILL_35,
    FILL_40,
    FILL_45,
    FILL_50,
    FILL_55,
    FILL_60,
    FILL_65,
    FILL_70,
    FILL_75,
    FILL_80,
    FILL_85,
    FILL_90,
    FILL_95,
    FILL_FULL_FOAM,
    FILL_DRAINING,
    FILL_UNAVAILABLE
}

fun fillDisplayFor(frame: PintFrame): Pair<PintFillAsset, String> = when (frame) {
    PintFrame.Unavailable -> PintFillAsset.FILL_UNAVAILABLE to "—"
    is PintFrame.Steady -> PintFillAsset.entries[frame.progress.fillBucket] to frame.progress.completed.toString()
    is PintFrame.FullBubbles -> PintFillAsset.FILL_FULL_FOAM to frame.completed.toString()
    is PintFrame.Draining -> PintFillAsset.FILL_DRAINING to frame.completed.toString()
}
